name: custard-ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/custard/test/**
  pull_request:
    paths-ignore:
      - .github/custard/test/**

jobs:
  affected:
    uses: GoogleCloudPlatform/cloud-samples-tools/.github/workflows/affected.yaml@9ee708234e240605d96e78f652c333ed6aa95a23 # v0.4.0
    permissions:
      statuses: write
    with:
      head-sha: ${{ github.event.pull_request.head.sha || github.sha }}
      config-file: .github/custard/config.jsonc
      custard-version: v0.4.0 # TODO: this should be auto-updated in the reusable workflow in cloud-samples-tools
      # No need to create checks since this is a pull_request workflow.
      create-check-if: false

  lint:
    needs: affected
    uses: ./.github/workflows/lint.yaml
    if: needs.affected.outputs.paths != '[]'
    with:
      head-sha: ${{ github.event.pull_request.head.sha || github.sha }}
      paths-json: ${{ needs.affected.outputs.paths }}
